### ISSUE TITLE
Invalid redirect after "Play Tutorial" button press

### ISSUE THREAD

**Issue by bocharsky-bw** [knpuniversity/phpstorm#2]
On [Lean and Mean Dev with PhpStorm (for Symfony)](https://knpuniversity.com/screencast/phpstorm) page after **Play Tutorial** button press I forwarding to:
**Expected:** [Setup](https://knpuniversity.com/screencast/phpstorm/setup) page
**Actual:** [Annotations](https://knpuniversity.com/screencast/phpstorm/annotations) page

**Result** I could finished this tutorial navigating left sidebar menu, the Setup item in menu shows as not passed.

**Comment by weaverryan** [comment]
@bocharsky-bw hmm - so you were taken to "Annotations", but there in the left sidebar menu, there was no checkmark next to Setup. Is that correct?

**Comment by bocharsky-bw** [comment]
A bit wrong, I _always_ redirecting to "Annotations" page after I pressed "Play Tutorial" button.

**NOTE:** I redirecting to "Annotations" page skipping "Setup" only when I loggined in. For unauthorized user the "Play Tutorial" button works fine.

**Comment by bocharsky-bw** [comment]
Oh, my bad, it seems the application try to resume tutorial and redirect me to the last page passed by my user. I don't know it. What about checkbox - I'm not sure, maybe I was unauthorized.
Anyway I can't reproduce it now. I think we could close this issue, sorry

**Comment by weaverryan** [comment]
Yep - there's a resume functionality. I'll take a look and make sure its logic "makes sense". It's nice, but can be surprising :)

**Comment by bocharsky-bw** [comment]
@weaverryan Resume functionality is awesome! What about to change button name with "Resume Tutorial" isntead of "Play Tutorial" if user already starts this course? I think it will be allow to avoid surprising for authorized users :)

**Comment by weaverryan** [comment]
Good idea - I just made that change :)

**Comment by bocharsky-bw** [comment]
Thanks a lot for quick improvement, it's more clearer now! )
